apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis
