apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-data
  namespace: {{ include "database.name" . }}-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
      