apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: {{ include "database.name" . }}-system
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres