kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  # Reservations-Api
  - containerPort: 3000
    hostPort: 3000
  # Reservations-Api debug
  - containerPort: 4000
    hostPort: 4000
  # Database
  - containerPort: 5432
    hostPort: 5432