app:
  version: ""

  replicaCount: 1

  resources:
    limits:
      cpu: 500m
    requests:
      cpu: 500m

worker:
  version: ""

  replicaCount: 1

  resources:
    limits:
      cpu: 500m
    requests:
      cpu: 500m